### ISSUE TITLE
请问要如何在python文件中import并使用呢，有示例代码吗

### ISSUE THREAD

**Issue by cherryoyo** [RyouMon/autosub-baidu#1]
请问要如何在python文件中import并使用呢，有示例代码吗？

**Comment by RyouMon** [comment]
# 1 安装 autosub-baidu
```
pip install autosub-baidu
```

# 2 参考这个文件
https://github.com/RyouMon/video-from-audio-webp/blob/03981de2e64e1205d985e2a3ecd37387a4bff88b/utils/generators.py#L8

**Comment by cherryoyo** [comment]
非常感谢您的回复，但是看了文档后我还是不太理解，仍然无法使用。
主要还是由于我现在还是初学，水平太低。。。
最近也用到了moviepy，看了他下面的这种示例代码后，我就知道如何使用了。
请问您可否提供一下类似这样的示例代码呢？


`from moviepy import *

video = VideoFileClip("myHolidays.mp4").subclip(50,60)


txt_clip = ( TextClip("My Holidays 2013",fontsize=70,color='white')
             .with_position('center')
             .with_duration(10) )

result = CompositeVideoClip([video, txt_clip]) # Overlay text on video
result.write_videofile("myHolidays_edited.webm",fps=25) # Many options...
`

**Comment by RyouMon** [comment]
```py
import sys
from pprint import pprint

from autosubb import generate_subtitles

# 下面三个替换成你的
APP_ID = '2*****0'
API_KEY = 'W********************o'
SECRET_KEY = 'X******************************5'

filename = 'audio.mp3'


def main():
    subtitles = generate_subtitles(
        source_path=filename, app_id=APP_ID, api_key=API_KEY, secret_key=SECRET_KEY, concurrency=2,
        dev_pid='80001',
    )
    pprint(subtitles)


if __name__ == '__main__':
    sys.exit(main())
```

输出：
```
Converting speech regions to WAV files: 100% |##################| Time: 0:00:00
Performing speech recognition: 100% |###########################| Time: 0:00:09
[((2.3040000000000003, 4.608000000000002), '从前有一对仙人夫妻。'),
 ((5.376000000000003, 7.424000000000005), '他们常常到山顶上下棋。'),
...
 ((56.83200000000004, 59.392000000000046), '猴子的眼睛一直盯着这盘水蜜桃。'),
 ((60.41600000000005, 63.48800000000005), '战胜对手，其实就是战胜对手的弱点。')]
```

**Comment by cherryoyo** [comment]
谢谢你的回复，使用了这段代码后，出现了这个错误：

`
for i, transcript in enumerate(pool.imap(recognizer, extracted_regions)):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
Exception: SpeechRecognizer: request qps too much, err_code: 3304
`



另外，我尝试使用命令行运行，又收到了这样的错误：

`

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
`

百度api的开通情况应该是正常的
<img width="1461" alt="截屏2021-12-29 上午9 10 19" src="https://user-images.githubusercontent.com/77727525/147618130-52607964-f837-4ede-9d39-ae1eef5ea8e1.png">
<img width="1433" alt="截屏2021-12-29 上午9 12 33" src="https://user-images.githubusercontent.com/77727525/147618205-c5092d0a-b3fc-49a8-9946-027e9fcb2f87.png">

**Comment by cherryoyo** [comment]
可以输出了，谢谢🙏

**Comment by cherryoyo** [comment]
不好意思，还有2个问题想要请教。
1.示例代码打印带有起始和结束的时间以及字幕是没有问题了，请问如何输出srt文件呢。
2.由于是要用在短视频中，目前字幕太长，字幕中每句的文字数量能否调整。比如遇到逗号等符号就分隔。
