### ISSUE TITLE
不好意思，还有2个问题想要请教。

### ISSUE THREAD

**Issue by cherryoyo** [RyouMon/autosub-baidu#2]
不好意思，还有2个问题想要请教。
1.示例代码打印带有起始和结束的时间以及字幕是没有问题了，请问如何输出srt文件呢。
2.由于是要用在短视频中，目前字幕太长，字幕中每句的文字数量能否调整。比如遇到逗号等符号就分隔。

_Originally posted by @cherryoyo in https://github.com/RyouMon/autosub-baidu/issues/1#issuecomment-1004481919_

**Comment by RyouMon** [comment]
1. 保存SRT文件可以这样写：
```py 
import autosubb

subtitles = [
    ((2.3040000000000003, 4.608000000000002), '从前有一对仙人夫妻。'),
    ((5.376000000000003, 7.424000000000005), '他们常常到山顶上下棋。'),
]

with open('subtitle.srt', 'wb') as f:
    srt_file = autosubb.formatters.srt_formatter(subtitles)
    f.write(srt_file.encode('utf-8'))
```

2. 第二个问题需要你自己处理，我的思路是：
遍历字幕列表，如果字幕太长就在合适的位置插入一个换行符：`\n`。
这个方案我没有写过，需要你自行验证。

**Comment by cherryoyo** [comment]
谢谢，您的代码。
关于第二种方式，我的思路跟你的差不多，是用fenci方式在合适的位置分隔句子，
然后根据一句话的时长，推断分隔后句子的起始时间，重新写入字幕。
我会尝试实现一下试试看。
